WORD_UPPERCASE_NONE = 0
WORD_UPPERCASE_CAPITALIZE = 1
WORD_UPPERCASE_UPPER = 2

WORD_UPPERCASE_POSSIBILITIES = [WORD_UPPERCASE_NONE, WORD_UPPERCASE_CAPITALIZE, WORD_UPPERCASE_UPPER]

MESSAGE_TRIGGER_NONE = 0
MESSAGE_TRIGGER_OFFENSIVE = 1  # As in, an offensive word.
MESSAGE_TRIGGER_PERSUASIVE = 2
MESSAGE_TRIGGER_DEFENSIVE = 4  # As in crying.
MESSAGE_TRIGGER_PARENT = 8  # As in, lecture.
MESSAGE_TRIGGER_AWE = 16
MESSAGE_TRIGGER_PRAISE = 32  # As in, fanatical awe.
MESSAGE_TRIGGER_DISSAPOINTMENT = 64
MESSAGE_TRIGGER_CURSE = 128
MESSAGE_TRIGGER_SHOUT = 256

MESSAGE_TRIGGER_POSSIBILITIES = [MESSAGE_TRIGGER_NONE, MESSAGE_TRIGGER_OFFENSIVE, MESSAGE_TRIGGER_PERSUASIVE,
                                 MESSAGE_TRIGGER_DEFENSIVE, MESSAGE_TRIGGER_PARENT, MESSAGE_TRIGGER_AWE,
                                 MESSAGE_TRIGGER_PRAISE, MESSAGE_TRIGGER_DISSAPOINTMENT, MESSAGE_TRIGGER_CURSE,
                                 MESSAGE_TRIGGER_SHOUT]

DELIMETERS = [".", "!", "?", ",", "", ":"]
DELIMETERS_SENTENCE_END = [".", "!", "?"]

LEFT_ARROW_SYMBOL = "\u2190"
UP_ARROW_SYMBOL = "\u2191"
RIGHT_ARROW_SYMBOL = "\u2192"
DOWN_ARROW_SYMBOL = "\u2193"

NAME_LETTERS = ["A", "a"]  # Is used when we have a name collision.

POS_NAMES = ["Andrew", "Ann", "Arnold", "Amy",
			 "Barney", "Bob", "Bill",
			 "Jebediah", "Jimmy"]
POS_SURNAMES = ["Aqua",
				"Black",
				"Jasper"]
