# Maximum distance multiplier(from max) for Ideo_Modifier to be even considered.
IDE_MOD_MAX_DIST_MULT = 0.0001

IDE_OFF_CHARTS_LEFT = 200
IDE_EXTREME_LEFT = 100
IDE_RADICAL_LEFT = 50

IDE_NONE = 0

IDE_OFF_CHARTS_RIGHT = -200
IDE_EXTREME_RIGHT = -100
IDE_RADICAL_RIGHT = -50

IDE_MAX_VALUE = IDE_OFF_CHARTS_LEFT
IDE_MIN_VALUE = IDE_OFF_CHARTS_RIGHT
